[package]
name = "engyn"
version = "0.1.0"
authors = ["Remco Kranenburg <remco@burgsoft.nl>"]

[dependencies]
cgmath = "*"
conrod = { version = "*", features = ["glium", "winit"] }
glium = { version = "*", features = ["glutin"] }
image = "*"
rand = "*"
rust-webvr = "*"
time = "*"
tobj = "*"
